### PR TITLE
feat(lang): added php support

### PR DESCRIPTION
**Pull request by hacktivista**
Configures tree-sitter, phpactor as LSP server and xdebug/vscode-php-debug as DAP server.

### CODE REVIEW

**Comment by hacktivista** [comment]
I never wrote Lua before, nor ever configured NeoVim nor lazy.nvim. I just looked at other language configs and tried to do the same, it worked surprisingly well, but probably there are some things that could be improved, so please review it thoroughly.

Thanks for this project!

**Comment by willopez** [comment]
It would be great to have this feature!

**Comment by madflow** [comment]
This is one flavour of PHP suppport, which would be highly appreciated. However: The more mature LSP server is in my opinion "intelephense". phpactor is great, too. Maybe this can made configurable? or optional? It is a matter of taste, I suppose.

For testing there is also a neotest adapter, which would fit into the Lazyvim ecosystem:

* https://github.com/olimorris/neotest-phpunit

**Comment by willopez** [comment]
I have created a custom plugin using the config on this PR and it's working great! I prefer to use Phpactor as it's free and has many features. For anybody interested, here is my config. https://github.com/willopez/LazyVim/blob/main/lua/plugins/php-lsp.lua

**Comment by gmnz** [comment]
I work as a web dev (using php a lot) and found this combination to be working pretty well:

- lsp: intelephense (it has limited features if you don't buy a license, but I've tried the alternatives and they didn't seem to work properly after installed by Mason)
- linter: phpcs (first one I got to work and was able to set a coding standard using args)
- formatter: pretty-php (first one I got to work and was able to set a coding standard args)

I've set both formatter and linter to follow psr12 so that the linter doesn't complain about how the formatter is formatting.

Just wanted to share my experience and maybe get some inspiration for improving my config from other php devs. :-)

**Comment by Tmeister** [comment]
@gmnz 

You may want to share your configuration, so everyone interested can take a look.

**Comment by gmnz** [comment]
@Tmeister 

```lua
return {
  "mfussenegger/nvim-lint",
  opts = function(_, opts)
    local phpcs = require("lint").linters.phpcs
    phpcs.args = {
      "-q",
      "--standard=PSR12",
      "--report=json",
      "-",
    }
    --
    opts.linters_by_ft = vim.tbl_extend("force", opts.linters_by_ft, {
      php = { "phpcs" },
    })

  end,
}
```

```lua
return {
  {
    "stevearc/conform.nvim",
    opts = function(_, opts)
      opts.formatters_by_ft = vim.tbl_extend("force", opts.formatters_by_ft, {
        php = { { "pretty-php", }, },
      })

      opts.formatters = vim.tbl_extend("force", opts.formatters, {
        ["pretty-php"] = {
          prepend_args = {
            "--psr12",
          },
        },
      })
    end,
  },
}
```

Any feedback on this is welcome, I'm not an expert on lua nor linters, nor formatters. :-)

**Comment by MystikReasons** [comment]
Are there any updates regarding PHP support?

**Comment by willopez** [comment]
I use a lot of PHP, WordPress and for other projects, it would be great to have PHP support! @folke thanks a lot for your work!

**Comment by folke** [comment]
Updated and merged. Thanks!

**Comment by esetnik** [comment]
@folke what's the recommended approach for language extras that have multiple good variants for lsp? For example, the lang extra now merged in this PR uses `phpactor` but a lot of php devs use `intelephense` instead. I tested it out today and the two seem to be able to coexist peacefully (e.g. they can both be enabled simultaneously) although i'm not sure about whether this is actually a good idea. 

It feels a bit weird to me that the LazyVim community would need to be opinionated about which lsp is the best for a particular language. Is there a value to having language variants in extras, e.g. `lang.php-phpactor` and `lang.php-intelephense`? Are there other languages which have multiple good lsp implementations that should be considered?

**Comment by dpetka2001** [comment]
You can take a look at [Python Extra](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/lang/python.lua) about taking into considerations different variants of which LSP server will be used. Of course the users can add whatever they want to their personal configurations as well. 

The Extras are mostly best effort setups in my opinion and it depends on the PR creator's experience with the language as well. It's not a be-all/end-all kind of thing. 

If you think you can improve some Extra, then just make a PR and it will either be accepted or not.

**Comment by folke** [comment]
Like @dpetka2001 says.

Feel free to submit a PR similar to how it's done in the pyhthon extra.

Ideally the php extra should default to the best LSP available, but since I don't do php anymore, I'm not the best person to decide on that.

**Comment by folke** [comment]
@esetnik if intelephense is better or more widely used, then feel free to make it the default

**Comment by muneebusmani** [comment]
[LSP] Format request failed, no matching language servers.
it says it all the time

**Comment by dpetka2001** [comment]
That's because no formatting has been set up for this Extra. Feel free to improve it.

**Comment by hacktivista** [comment]
Many people use intelephense and phpactor. I prefer phpactor because it uses a libre license, and does not require buying one for unlocking features. IMHO proprietary software should never be a default on a FLOSS project.

**Comment by muneebusmani** [comment]
It seems like there are 2 thing more to do in the this extra, configure formatting, Lin ing with the way python extra does, for formatting there could be 3 options ppl go for, php cs fixer, pint or pretty-php, and about linting there seems to be options in .phpactor.json for choosing phpstan and/or psalm, but there are other linters too like php codesniffer, tlint, etc

**Pull request merged**
