### PR TITLE
refactor(typescript): split typescript dap from lang

### PR DESCRIPTION
**Pull request by andresatierf**

### CODE REVIEW

**Comment by andresatierf** [comment]
You're right, I was only looking at the typescript extra. My reason was due to the lua `dap` being inside the dap folder, it made sense to me to do the same for the other languages.

**Comment by dpetka2001** [comment]
I believe the lua `dap` was put in there, because there is not a `lua` extra, since it's inherent.

**Comment by andresatierf** [comment]
I guess so... I still believe the dap configurations could be in its directory but I'll close this for now

**Comment by dpetka2001** [comment]
I'm not the one who'll make the decision on this. The maintainer will be. Just leave it open until he decides. I just asked for the logic behind this, maybe it was something I didn't understand.

**Comment by folke** [comment]
Makes more sense to stay in typescript lang.
And the lua thing is indeed confusing. Maybe I should move the nlua to a lua extra instead

**Pull request closed without merging**
