### PR TITLE
feat(util): add rainbow-delimiters

### PR DESCRIPTION
**Pull request by gacallea**
adding   "HiPhish/rainbow-delimiters.nvim" to utils

unsure if this is ui or util, feel free to comment/fix

cheers

### CODE REVIEW

**Comment by dpetka2001** [comment]
This one line isn't really worth of being an Extra of its own is it? Users can just install it in their personal config.

Just my humble personal opinion.

**Comment by gacallea** [comment]
> This one line isn't really worth of being an Extra of its own is it? Users can just install it in their personal config.
> 
> Just my humble personal opinion as a simple regular user.

I generally agree, and it is how I use it for now. However, it just popped in the Clojure lang extra so I thought it may be worth adding an option for everyone? maybe?

**Comment by dpetka2001** [comment]
I didn't even see that, since I don't do clojure at all. In my personal opinion, it shouldn't even be there in the first place. The language Extras should contain relevant code for how to have an easy setup for a specific language and refrain from adding personal stylistic preferences and leave that up to the end user.

**Comment by gacallea** [comment]
> > This one line isn't really worth of being an Extra of its own is it? Users can just install it in their personal config.
> > Just my humble personal opinion as a simple regular user.
> 
> I generally agree, and it is how I use it for now. However, it just popped in the Clojure lang extra so I thought it may be worth adding an option for everyone? maybe?

agree 100%

@folke feel free to close this if rainbow delimiters should be left to the user. also, clojure should follow what @dpetka2001 said?

**Comment by dpetka2001** [comment]
@gacallea I'm just a regular user and stating my personal opinion. The maintainer has the final say and he can do whatever he feels is right for this project without needing to follow anything I say.

**Comment by gacallea** [comment]
> @gacallea I'm just a regular user and stating my personal opinion. The maintainer has the final say and he can do whatever he feels is right for this project without needing to follow anything I say.

I keep forgetting that. the amount of your collab and messaging on issue always tricks my mind for some reason :)

**Comment by dpetka2001** [comment]
You should just treat me like a regular user and even less experienced than you in programming (since I've only started learning programming about 5 months ago).

**Comment by folke** [comment]
I agree with @dpetka2001 and also just removed it from the clojure spec.
Thank you anyway!

**Comment by fernando-nubank** [comment]
Sorry I'm late to this issue but I'd like to add that for editing any LISP dialect rainbow parenthesis is not about style: there are many nested parenthesis because of s-exps and it makes it easier to not leave any them unbalanced

**Pull request closed without merging**
