### PR TITLE
perf(supermaven): add lazy-loading

### PR DESCRIPTION
**Pull request by manuuurino**
## Description

As title, somehow these events have been forgotten, ive checked the git history of it aswell. 

## Checklist

- [x] I've read the [CONTRIBUTING](https://github.com/LazyVim/LazyVim/blob/main/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by folke** [comment]
This doesn't really make sense, since creating those lazy loaded commands also has a cost.
Better to just load on `VeryLazy` instead if those commands are really that important.

**Comment by dpetka2001** [comment]
The only useful commands are `SupermavenUseFree/Pro`. The loading should be taken care of `nvim-cmp/blink` as their dependency. However, `vim.g.ai_cmp` should be moved inside blink's `opts`, so that the blink spec is still responsible for loading supermaven regardless of `vim.g.ai_cmp` in my personal opinion.

**Comment by dpetka2001** [comment]
Never mind just keep `InsertEnter` like copilot and maybe just the 2 commands? Or `VeryLazy` indeed.

**Comment by manuuurino** [comment]
Just updated it, ive decided to keep these two commands, so its steup is similar to its others like copilot and codeium

**Comment by folke** [comment]
ty

**Pull request merged**
