### PR TITLE
fix(clangd): update setup from upstream changes

### PR DESCRIPTION
**Pull request by amaanq**

### CODE REVIEW

**Comment by jla2000** [comment]
@amaanq Does this fix that clangd is currently not working in lang.clangd ? At least for me it is not in the configured servers list and no lsp is started.

**Comment by amaanq** [comment]
yeah clangd_extensions used to handle setting up the LSP, it no longer does. this is why looking for breaking change commits is important :)

**Comment by jla2000** [comment]
Ahh nice :D Is there a way for me to try it out already?

**Comment by amaanq** [comment]
clone my repo locally, ensure you have a proper dev pattern set and set `dev = true` for LazyVim

in your spec in lazy.lua this would work
```lua
    dev = { patterns = jit.os:find("Windows") and {} or { "amaanq", "LazyVim"} }
```

**Comment by jla2000** [comment]
How does using this dev pattern work? Do I have to set it in my own lazyvim config or in the cloned repository? What I want to achieve is use my current config but checking out LazyVim with your branch to get clangd working :)

**Comment by jla2000** [comment]
I figured it out, clangd works now again :D

**Comment by YF18021017353** [comment]
> I figured it out, clangd works now again :D

Hi, @jla2000. I had the same problem. How did you solve it?

**Comment by jla2000** [comment]
@YF18021017353
- In lazy.lua add `dev = true` to the "LazyVim/LazyVim" entry
- Clone the repo from amaanq to eg .~/projects and checkout the clangd-fix branch
- in lazy.lua inside the require("lazy").setup options table, add a new entry:

`dev = {
  path = "~/projects",
  patterns = jit.os.find("Windows") and {} or { "amaanq", "LazyVim" },
}`

**Comment by YF18021017353** [comment]
@jla2000 Thx, It works! :)

**Comment by surmish** [comment]
> @YF18021017353
> 
>     * In lazy.lua add `dev = true` to the "LazyVim/LazyVim" entry
> 
>     * Clone the repo from amaanq to eg. ~/projects and checkout the clangd-fix branch
> 
>     * in lazy.lua inside the require("lazy").setup options table, add a new entry:
> 
> 
> `dev = { path = "~/projects", patterns = jit.os.find("Windows") and {} or { "amaanq", "LazyVim" }, }`

`os.find` should be `os:find` I think

**Comment by grappas** [comment]
It's not working for me.

**Comment by jla2000** [comment]
> It's not working for me. Snippets are working but completion doesn't. Even with fix provided by @amaanq 

Did you create a proper compile_commands.json link?

**Comment by grappas** [comment]
Ummm... what do you mean?

**Comment by jla2000** [comment]
Its a link in your root folder that should point to a compile_commands.json, which for example could be generated by cmake. The clangd lsp will read this file to gather information about the code

**Comment by SuperCB** [comment]
I met the same problem

**Comment by folke** [comment]
thanks!

**Comment by grappas** [comment]
https://github.com/LazyVim/LazyVim/tree/release-please--branches--main--components--LazyVim

How to include/test it?

**Pull request merged**
