### PR TITLE
fix(keymaps): remove the extra '[]' around y

### PR DESCRIPTION
**Pull request by sgj123456**
## Checklist

- [x] I've read the [CONTRIBUTING](https://github.com/LazyVim/LazyVim/blob/main/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by arthur-mountain** [comment]
@sgj123456 I remember this was intentional, not a typo.

**Comment by sgj123456** [comment]
> @sgj123456 I remember this was intentional, not a typo.

I see, why?

**Comment by arthur-mountain** [comment]
@sgj123456 This might require asking the maintainer; [a PR](https://github.com/LazyVim/LazyVim/pull/3323) was previously opened regarding this.

**Comment by sgj123456** [comment]
> @sgj123456 This might require asking the maintainer; [a PR](https://github.com/LazyVim/LazyVim/pull/3323) was previously opened regarding this.

In that case, I'm going to close it.

**Pull request closed without merging**
