### PR TITLE
fix: bufferline does not refresh after close buffer

### PR DESCRIPTION
**Pull request by RayGuo-ergou**
### Description

Faced an issue that when close the buffer from bufferline (either right click or close icon). Some times the bufferline does not refresh after buffer close (not really sure why tho). This will cause a buffer id invalid error if try to close the buffer again.

I am not using lazyvim distro but I can reproduce this issue with lazyvim starter repo. 

image

### CODE REVIEW

**Comment by folke** [comment]
This was due to something else. Just fixed that

**Comment by RayGuo-ergou** [comment]
Hi @folke the new update does not seems to fix this issue.

GIF 5-18-2024 12-12-24 AM
_Yellow dot is left click and blue dot is right click_
image

**Comment by folke** [comment]
I just added the `BufDelete` as in your PR. Didnt want to merge yours, since it also changed the formatting of the dashboard text.

Thanks!

**Comment by RayGuo-ergou** [comment]
No problem. As long as the problem solved. Thanks!

**Pull request closed without merging**
