### PR TITLE
feat(treesitter-context): which-key toggle

### PR DESCRIPTION
**Pull request by stefanboca**
## Description

Add a which-key toggle for treesitter-context

## Screenshots

image

## Checklist

- [x] I've read the [CONTRIBUTING](https://github.com/LazyVim/LazyVim/blob/main/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by folke** [comment]
ty!

**Comment by dotfrag** [comment]
Why was the event changed? Is it really necessary?

**Comment by folke** [comment]
Missed that. Probably to make sure the mapping is always available?
However, that shouldnt be needed indeed.

**Comment by dpetka2001** [comment]
It works totally fine with `LazyFile` as well. But does it really matter in the end? `LazyFile` is just an alias for `{ "BufReadPost", "BufNewFile" }` in the end. `VeryLazy` just happens after `Vim/UIEnter`.

**Comment by dotfrag** [comment]
Well, technically it's loaded later. Whether it makes a significant difference that's a different question :)

**Comment by folke** [comment]
Either way is fine. Not a big difference indeed

**Comment by folke** [comment]
Unless that was needed to make it work properly when opening a file from the cmdline?

**Comment by dpetka2001** [comment]
I tested with `LazyFile` and opening Neovim with a file argument and it still worked for me. But even Treesitter doesn't actually load on `LazyFile` even though it's defined in its `event`. It either loads on `VeryLazy` or as a `start` plugin when opening with a file argument, so `LazyFile` isn't even needed there I believe? But whatever.

**Comment by folke** [comment]
LazyFile is still needed for a bunch of plugins to make it work properly when opening a file from the cmdline.

**Comment by dpetka2001** [comment]
Yes, probably. I did say that I may be missing something. But I was only aware of `nvim-lspconfig`, which will miss the `FileType` event on the first file if it's loaded on `VeryLazy` while opening Neovim with a file argument and thus won't have any LSP attached. There might be other plugins that behave like that for sure.

**Comment by stefanboca** [comment]
> Missed that. Probably to make sure the mapping is always available? However, that shouldnt be needed indeed.

You're correct that I changed the event to keep the mapping always available, eg. on the dashboard, and for the toggle state to always be correct. Previously the plugin was also loaded on the key `<leader>ut`, but I wasn't sure how to preserve that while keeping the code simple (I used the `mini.animate` extra as reference for the toggle mapping).

**Pull request merged**
