### PR TITLE
esc closes telescope without intermediate normal mode

### PR DESCRIPTION
**Pull request by navxio**
Hey @folke!!

Reduces 1 `<Esc>` keypress while exiting telescope.

### CODE REVIEW

**Comment by folke** [comment]
I'm not a fan of this. How would you enter normal mode in telescope then?

You can of course add this to your own config.

**Comment by gary-ruizhang** [comment]
add below config inside init.lua, don't know how to config this in LazyVim style.

**Comment by gary-ruizhang** [comment]
Add below into init.lua, don't know how to do this in LazyVim style.

`local actions = require("telescope.actions")

require("telescope").setup({
    defaults = {
        mappings = {
            i = {
                ["<esc>"] = actions.close,
            },
        },
    },
})`

**Comment by gary-ruizhang** [comment]
Add below into init.lua, don't know how to do this in LazyVim style.

**Comment by gary-ruizhang** [comment]
Add below into init.lua, don't know how to do this in LazyVim style.

`local actions = require("telescope.actions")

require("telescope").setup({
    defaults = {
        mappings = {
            i = {
                ["<esc>"] = actions.close,
            },
        },
    },
})`

**Comment by gary-ruizhang** [comment]
Add below into init.lua, don't know how to do this in LazyVim style.

```
local actions = require("telescope.actions")

require("telescope").setup({
    defaults = {
        mappings = {
            i = {
                ["<esc>"] = actions.close,
            },
        },
    },
})
```

**Comment by gary-ruizhang** [comment]
```
return {
  {
    "nvim-telescope/telescope.nvim",
    opts = {
      defaults = {
        mappings = {
          i = {
            ["<Esc>"] = function(...)
              return require("telescope.actions").close(...)
            end,
          },
        },
      },
    },
  },
}
```

**Pull request closed without merging**
