### PR TITLE
feat(typescript): add typescriptreact/javascriptreact to types

### PR DESCRIPTION
**Pull request by OneOfOne**

### CODE REVIEW

**Comment by folke** [comment]
tsserver settings can only be javascript or typescript. See here: https://github.com/typescript-language-server/typescript-language-server#workspacedidchangeconfiguration

Are you sure those things for dap are also needed?

**Comment by OneOfOne** [comment]
I'm sure about dap, without it:
Screenshot_20231003_143813

**Comment by folke** [comment]
Can you completely undo to settings changes? It's better for the generated docs

**Comment by OneOfOne** [comment]
> Can you completely undo to settings changes? It's better for the generated docs

done in https://github.com/LazyVim/LazyVim/pull/1574/commits/bfb47ccf4f0373535851c2971a78b86d18b01966

**Comment by folke** [comment]
thanks!

**Pull request merged**
