### PR TITLE
feat(plugins): add terraform extra lang

### PR DESCRIPTION
**Pull request by azdanov**

### CODE REVIEW

**Comment by robsonpeixoto** [comment]
I'm using exactly this config for.a long time and works like a charm.

**Comment by folke** [comment]
thanks!

**Comment by Mjb141** [comment]
This doesn't work for me @folke - I _always_ get `terraformls: timeout`. Is there something I'm missing? Terraform-ls is installed via homebrew.

**Comment by folke** [comment]
@Mjb141 I have no idea. I don't use terraform.

**Comment by robsonpeixoto** [comment]
@folke what's the best way to change the `mini.comment`'s `custom_commentstring` options?

For some reason `mini.comment` is detecting the `commentstring`, [maybe because has 3 differents options](https://github.com/MichaHoffmann/tree-sitter-hcl/blob/becebebd3509c02e871c99be55556269be1def1b/make_grammar.js#L347-L354), and IMHO a good hack is change the  `custom_commentstring`.

Do you have a suggestion of how to allow the extra plugins extends it?
https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/coding.lua#L138-L148

**Comment by folke** [comment]
Assuming Treesitter doesn't properly get the commentstring, the easiest would be to create an autocmd for the hcl filetype that sets the correct `commentstring` option for the buffer

**Comment by reegnz** [comment]
https://github.com/JoosepAlviste/nvim-ts-context-commentstring/pull/94 is trying to fix the commentstring situation.

**Comment by reegnz** [comment]
My nvim-ts-context-commentstring change got merged, cutting a PR to drop the custom handing in lazyvim.

**Pull request merged**
