### PR TITLE
feat(extras): add database support

### PR DESCRIPTION
**Pull request by muneebusmani**
Dadbod UI integration For LazyVim

### CODE REVIEW

**Comment by Conarius** [comment]
Oh with the optional part I meant
```lua
optional = true,
```
right after the plugin name, not as `opts.optional = true`

**Comment by muneebusmani** [comment]
@folke will this get merged?

**Comment by rubiin** [comment]
this is a duplicate of https://github.com/LazyVim/LazyVim/pull/1740

**Comment by muneebusmani** [comment]
ok then would that get merged?

**Comment by rubiin** [comment]
That depends on the maintainer :)

**Comment by muneebusmani** [comment]
well i had two other things in mind for a pr but seeing these 60+ open pr's i dont think those will get merge either

**Comment by rubiin** [comment]
Well he does manage alot of open source projects with 100+ prs open so I guess the delay is slef explanatory :)

**Comment by muneebusmani** [comment]
oh now i remember he has alot of repos, thats okay, i will open my dart and laravel pr's , for lazy extra

**Comment by igorgue** [comment]
@muneebusmani dunno which one would get merged, mine is quite old...

I have this plugin that you don't have:

```lua
{ "jsborjesson/vim-uppercase-sql", ft = sql_ft },
```

Really like it because the SQL convention is all UPPERCASE keywords and I don't type like that (I have capslock obviously mapped to ctrl).

**Comment by muneebusmani** [comment]
Does completions work in your pr like does sql lsp gets attached into the query window?

**Comment by igorgue** [comment]
@muneebusmani I'm not sure if it uses an LSP but I also included this: `vim-dadbod-completion` like your pr does. Are you looking into getting diagnostics? I see there are a few LSPs in the mason registry for SQL but I haven't tried any of them.

**Comment by folke** [comment]
Closing in favor of #1740
Thank you anyway!

**Pull request closed without merging**
