### PR TITLE
feat(docs): add link to LazyVim For Ambitious Developers to README

### PR DESCRIPTION
**Pull request by dusty-phillips**
As requested, here's a link to my book from the README. I'll add the video and this link to the main page of lazyvim.org as well.

### CODE REVIEW

**Comment by rubiin** [comment]
You should reword the commit to something like `doc(readme): Add link to LazyVim For Ambitious Developers to README` for the CI to pass :)

**Comment by folke** [comment]
Thanks!

**Comment by dusty-phillips** [comment]
I don't think I've ever had a PR merge that fast, even when I was the one merging it. 🤯

**Comment by rubiin** [comment]
> I don't think I've ever had a PR merge that fast, even when I was the one merging it. 🤯

another reason to use lazyvim

**Comment by folke** [comment]
PR's without code are pretty easy to review ;)

**Pull request merged**
