### PR TITLE
fix: disable ruff hover correctly

### PR DESCRIPTION
**Pull request by fecet**
image

The hover ability of ruff seems not be correctly disabled.

### CODE REVIEW

**Comment by lkhphuc** [comment]
A more general way if using noice would be
```
 { "folke/noice.nvim",
    opts = {
      routes = {
        {
          filter = {
            event = "notify",
            any = {  { find = "No information available"} }
          }
        }
      },
    },
  }
```

**Comment by fecet** [comment]
This approach is better if we actually don't want to disable hover of ruff completely, is that the case here?

**Comment by dpetka2001** [comment]
The `setup` in the original code is outside of `opts`. See [here](https://github.com/LazyVim/LazyVim/blob/566049aa4a26a86219dd1ad1624f9a1bf18831b6/lua/lazyvim/plugins/extras/lang/python.lua#L12-L26). So it's not a problem with the `setup` itself not working. I have it like the original code configured and it works correctly with the `setup`. Would you mind changing your PR to the original code, but put `setup` inside `opts` so that it does take effect?

**Comment by fecet** [comment]
Hi @dpetka2001. I'm new to lazyvim, did you mean change it to 
```
opts = {
      servers = {
        pyright = {},
        ruff_lsp = {},
      },
setup = {
      ruff_lsp = function()
        require("lazyvim.util").on_attach(function(client, _)
          if client.name == "ruff_lsp" then
            -- Disable hover in favor of Pyright
            client.server_capabilities.hoverProvider = false
          end
        end)
      end,
}
    },
    
```

**Comment by dpetka2001** [comment]
Yes exactly. Does that work for you in your local environment? It should in my opinion.

**Comment by fecet** [comment]
> Yes exactly. Does that work for you in your local environment? It should in my opinion.

yeah this works perfexrly

**Comment by folke** [comment]
thanks!

**Pull request merged**
