### PR TITLE
feat(neo-tree): update to v3.x and change `follow_current_file` to a …

### PR DESCRIPTION
**Pull request by dpetka2001**
…table and enable it

### CODE REVIEW

**Comment by Mayrixon** [comment]
In the `init` section, the line `vim.g.neo_tree_remove_legacy_commands = 1` could also be removed because Neo-tree drops support for old commands.

**Review by Mayrixon — CHANGES_REQUESTED** [review]
In the init section, the line vim.g.neo_tree_remove_legacy_commands = 1 could also be removed because Neo-tree drops support for old commands.

**Comment by folke** [comment]
I've also removed the legacy commands and nerd font v3 icons

**Comment by folke** [comment]
thanks!

**Pull request merged**
