### PR TITLE
fix wierd Tmux/terminal esc-j/k line move issue

### PR DESCRIPTION
**Pull request by rjshrjndrn**
More details: https://github.com/LazyVim/LazyVim/discussions/163

### CODE REVIEW

**Comment by dpetka2001** [comment]
Are you sure this is the correct solution? From Neovim's [wiki](https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed) they suggest setting `escape-time` in `.tmux.conf`. `timeoutlen` seems like a personal choice and I prefer it being low, otherwise `which-key` gets really slow.

**Comment by rjshrjndrn** [comment]
I think so. Because all the other solutions I tried, have `esc j/k` issue. 
I think it's okay to keep it as default, and if someone is okay with the occasional esc j/k issue or doesn't use esc key much, can tweak the value to be smaller?

**Comment by dpetka2001** [comment]
I see what you're saying. Anyway I'm not the one to decide. Just expressed my opinion. The maintainer will make the decision. Even if it does end up being default, I'm ok with lowering the value myself since I don't use tmux that much.

**Comment by folke** [comment]
Won't merge this, since it would change the behavior of whichkey. closing

**Pull request closed without merging**
