### PR TITLE
Feat(extras): Add Database Support

### PR DESCRIPTION
**Pull request by muneebusmani**
Added Dadbod UI for Database Support, As far as i know it works with either .env file present or With and Environment Variable present for that

### CODE REVIEW

**Comment by dpetka2001** [comment]
Similar to #1740.

**Comment by muneebusmani** [comment]
so you mean this wont get approved?

**Comment by dpetka2001** [comment]
No, I'm not saying anything. I'm just a regular user like you. The maintainer makes the decision if something gets approved or not. I'm just noting that there's already a quite similar PR. No idea which one the maintainer will prefer.

**Comment by dpetka2001** [comment]
You also synced your forked repo with main LazyVim repo and your PR now contains changes irrelevant to this. You should try to use different branches instead of the main for future PRs and only update your main branch in your forked repo, so your other branches with your PRs don't get polluted by irrelevant changes.

**Comment by dpetka2001** [comment]
No problem. I just mentioned it for future reference. It'll be easier if you use separate branches for your PRs in your forked repo and only sync your main branch with LazyVim's repo.

Again, I'm just a regular user like you. So, no need to apologize to me. It just doesn't feel right. I'm not saying these things to scold you. I'm just mentioning these, so you're aware in the future.

**Comment by Conarius** [comment]
edgy.nvim should also have 
```lua
optional = true,
```
in there since it's an extra

**Comment by muneebusmani** [comment]
> No problem. I just mentioned it for future reference. It'll be easier if you use separate branches for your PRs in your forked repo and only sync your main branch with LazyVim's repo.
> 
> Again, I'm just a regular user like you. So, no need to apologize to me. It just doesn't feel right. I'm not saying these things to scold you. I'm just mentioning these, so you're aware in the future.

thanks for the tips , i will keep this in mind when doing something next time

**Comment by muneebusmani** [comment]
im gonna close this pr and and reopen it with only relevant changes since all of the features for Dadbod ui are integrated into it

**Comment by muneebusmani** [comment]
#3425 Check these changes now the history is much cleaner

**Pull request closed without merging**
