### PR TITLE
fix(blink): remove compatibility with 0.7.6 release

### PR DESCRIPTION
**Pull request by igorgue**
## Description

With the version update 5 mins ago, I got an error with this setting.

I'm not sure if removal is the correct way to fix this but it does runs well on my local.

- [x] I've read the [CONTRIBUTING](https://github.com/LazyVim/LazyVim/blob/main/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by dpetka2001** [comment]
Yes, this was only needed for as long as 0.7.6 was the latest stable release. It shouldn't be needed any more now that 0.8.0 is the latest stable release.

**Comment by dpetka2001** [comment]
By the way do you use Luasnip? If yes, do you observe duplicate snippets?

**Comment by folke** [comment]
ty

**Comment by surmish** [comment]
Can you author a release for this?

**Comment by igorgue** [comment]
> By the way do you use Luasnip? If yes, do you observe duplicate snippets?

Not really, I saw this behavior and decided to just use the builtin snippets and remove Luasnip's extra.

**Pull request merged**
