### PR TITLE
feat(core): open official website

### PR DESCRIPTION
**Pull request by arthur-mountain**
## Description
To make the LazyExtra float more convenient, sometimes, before enabling or disabling it, I want to check which plugins are included in this extra. Currently, I have to go online to search for LazyVim documentation and then search for this extra.

Please try to add a key event to open the official LazyVim extra page in the browser.

Additionally, please add a user command for a quicker and easier way to open the LazyVim website.

## Related Issue(s)

N/A!

## Screenshots

N/A!

## Checklist

- [x] I've read the [CONTRIBUTING](https://github.com/LazyVim/LazyVim/blob/main/CONTRIBUTING.md) guidelines.

## Additional Message to leave for the Maintainer

If it's okay to use the user command method, I would like to ask if you have any suggestions for which icon to use in `lua/lazyvim/plugins/ui.lua`. I'm currently unsure about which one looks better.

### CODE REVIEW

**Comment by arthur-mountain** [comment]
> I honestly don't believe this is actually needed in my personal opinion.


ohohoh, I'm not sure if it's useful XDDD

Initially, my main goal was to add a feature to LazyExtra that allows users to easily open the official website with the correct extra in the browser. 

I thought LazyVimDocument could be added as well, but it wasn't the primary feature I intended to contribute at the beginning.

**Comment by dpetka2001** [comment]
Both features are superfluous if you ask me. But it's up to the maintainer.

**Comment by arthur-mountain** [comment]
> Both features are superfluous if you ask me. But it's up to the maintainer.

Sure! Because sometimes before I enable/disable an extra, I want to check which plugins it contains, but currently, I need to search for them in the browser. So, 😆 

But sure, let's leave it to the maintainer to confirm.

**Comment by folke** [comment]
Not interested in this, but ty anyway!

**Comment by arthur-mountain** [comment]
Of course, no problem. 😄  Thank you very much for replying!!!

**Pull request closed without merging**
