### PR TITLE
fix(extra-lang-php): formatting and linting

### PR DESCRIPTION
**Pull request by muneebusmani**
Fixed the issue of php formatting not working in extras.lang.php

### CODE REVIEW

**Comment by muneebusmani** [comment]
Does it pair best with laravel? Idk I don't do symphony so idk about php codesniffer and php cs fixer, as I started laravel I heard about pint by laravel and pretty php because I was trying to get prettier like formatting for php so I pretty much prefer any of these two for formatting and about linting, phpstan and psalm is used by phpactor as a extension for the lsp and phpstan has a laravel variant called larastan and psalm has a plugin for laravel, as I stated below, these are all for laravel idk about Symphony, maybe we can make two extras one for symphony and one for laravel, which both extends php extra and give any of the preferred formatter and linter for php, ig it isn't as complicated as I am making it

**Comment by muneebusmani** [comment]
Does it pair best with laravel? Idk I don't do symphony so idk about php codesniffer and php cs fixer, as I started laravel I heard about pint by laravel and pretty php because I was trying to get prettier like formatting for php so I pretty much prefer any of these two for formatting and about linting, phpstan and psalm is used by phpactor as a extension for the lsp and phpstan has a laravel variant called larastan and psalm has a plugin for laravel, as I stated below, these are all for laravel idk about Symphony, maybe we can make two extras one for symphony and one for laravel, which both extends php extra and give any of the preferred formatter and linter for php, ig it isn't as complicated as I am making it

**Comment by folke** [comment]
php-cs-fixer doesn't need Symphony I believe?

**Comment by madflow** [comment]
> I would vote for PHP-CS-Fixer as the best maintained project by the Symfony ecosystem.

I meant that is "maintained" by the ecosystem. This yields sustainability. It is not specfific to Symfony - nor should it be.

**Comment by muneebusmani** [comment]
I just searched about Symphony and other frameworks, psalm and phpstan both have plugins for many frameworks and both can be used together because both work a little differently, I vote for phpstan and/or psalm for linting, and pretty php or pint for formatting, ik you guys didn't know these, trust me I used these stuff in all these in vscode phpstorm and neovim and these are the best

**Comment by folke** [comment]
@muneebusmani:

- php-pretty has **32** stars
- php-cs-fixer has **12600** stars

I think I'll trust the community on this.

`php-cs-fixer` works for any php project afaik.

**Comment by folke** [comment]
Also:

> Laravel Pint is an opinionated PHP code style fixer for minimalists. Pint is built on top of [PHP-CS-Fixer]> > > (https://github.com/FriendsOfPHP/PHP-CS-Fixer) and makes it simple to ensure that your code style stays clean and consistent.

So `pint` is basically `php-cs-fixer`

**Comment by muneebusmani** [comment]
@folke I never tried those so I can't really know the difference

**Comment by muneebusmani** [comment]
@madflow what do you think?

**Comment by madflow** [comment]
I think, that `php-cs-fixer` is the most mature project, and is best suited as a sensible default for an out-of-the-box Neovim config.

**Comment by muneebusmani** [comment]
I will see how it is implemented in python for more than one choice in formatter etc

**Comment by muneebusmani** [comment]
@folke @madflow  i searched about it , it isnt different, just a wrapper around it with the same amount of setting up psr standards or symphony standards, but it is also confirgured to follow laravel standards, i guess i will create a separate extra for laravel as it also needs a separate treesitter highlighting for blade files, lets just go with phpcs and phpcs-fixer, but how can i override these two for laravel extra?

**Comment by muneebusmani** [comment]
hold up dont merge yet, i am also adding linting @folke

**Comment by dpetka2001** [comment]
Shouldn't `mason` be its own spec instead of a dependency of `conform`? If someone uses `none-ls` instead of `conform` (conform disabled) will `mason` still install the tools? I believe the majority uses `conform` either way but I'm asking just in case.

**Comment by muneebusmani** [comment]
fixed it

**Comment by dpetka2001** [comment]
@muneebusmani That's not what I was talking about. I was asking if mason should be a spec on its own and not dependency of `nvim-lint` and `conform`. If someone has these 2 disabled and uses `none-ls` instead, will the tools still be installed by `mason`? But I'm not sure myself what will happen, that's why I asked the question. Hopefully maintainer can shed some light if this is actually needed or not.

**Comment by muneebusmani** [comment]
bruh why would anyone disable conform and nvim-lint?

**Comment by dpetka2001** [comment]
> bruh why would anyone disable conform and nvim-lint?

Then there's no need for `none-ls` as an Extra? We're just trying to provide users with choices, should they want to.

**Comment by muneebusmani** [comment]
@dpetka2001 is it okay now?

**Comment by dpetka2001** [comment]
I don't know. That's why I asked the question. I'm not 100% sure myself how it will behave. Why don't you just wait for the maintainer to give back feedback? Maybe it was needed, maybe not.

**Review by cjalvis — APPROVED** [review]

**Review by cjalvis — APPROVED** [review]

**Comment by folke** [comment]
Is phpcs really needed? phpactor already comes with diagnostics.

It can also be integrated with php-cs-fxer https://phpactor.readthedocs.io/en/master/integrations/php-cs-fixer.html

**Comment by muneebusmani** [comment]
I tried integrating it via .phpactor.json but they won't work unless they are installed and defined in the spec

**Comment by folke** [comment]
Merged, thanks!

**Comment by ahmedsayedabdelsalam** [comment]
great work 🚀, i think it would be nice if blade template engine files are supported too.

**Comment by muneebusmani** [comment]
Bruh u think I didn't try that, I spent a week trying to get blade files intellisense but it just won't work in neovim, either use phpstorm or vscode when doing blade files, I configured phpstorm and vscode to work the same way neovim works, the maximum you can get for blade files is syntax highlighting in nvim, nothing more

**Comment by eerison** [comment]
> Is phpcs really needed? phpactor already comes with diagnostics.
> 
> It can also be integrated with php-cs-fxer https://phpactor.readthedocs.io/en/master/integrations/php-cs-fixer.html

phpstan is almost an standard on php ecosystem.

thank you guys for the nice work <3

**Comment by eerison** [comment]
just for my information, is there any repo that contains php snippets?

**Comment by muneebusmani** [comment]
@eerison I don't know about any repo for that, and ig LazyVim has some builtin snippets via Friendly snippets plugin which is installed alongside LazyVim, that plugin has a lot of snippets for every other language

**Comment by tonysm** [comment]
I've been using pieces from this repo: https://github.com/kauffinger/lazyvim that adds Blade support and stuff, btw.

**Comment by muneebusmani** [comment]
@tonysm I also used pieces from this guy's repo it doesn't have blade intellisense but blade syntax highlighting

**Comment by eerison** [comment]
> @eerison I don't know about any repo for that, and ig LazyVim has some builtin snippets via Friendly snippets plugin which is installed alongside LazyVim, that plugin has a lot of snippets for every other language

friendly snippets works perfectly, keep generics snippets there looks a good approach  :)

**Comment by esetnik** [comment]
Does anyone know how to configure phpcs in LazyVim to use a specific coding standard or point to a custom phpcs.xml.dist? The defaults cause a ton of problematic diagnostics in our project.

**Comment by eerison** [comment]
> Does anyone know how to configure phpcs in LazyVim to use a specific coding standard or point to a custom phpcs.xml.dist? The defaults cause a ton of problematic diagnostics in our project.

Hey @esetnik 

I guess you could get support about this topic on phpactor repository
https://github.com/phpactor/phpactor/discussions

But I didn't see an option to choose a different phpcs config :/


I don't know if it could help you, But maybe you could create an `phpcs.xml` then phpcs gonna take this file first.

**Comment by esetnik** [comment]
> > Does anyone know how to configure phpcs in LazyVim to use a specific coding standard or point to a custom phpcs.xml.dist? The defaults cause a ton of problematic diagnostics in our project.
> 
> Hey @esetnik
> 
> I guess you could get support about this topic on phpactor repository https://github.com/phpactor/phpactor/discussions
> 
> But I didn't see an option to choose a different phpcs config :/
> 
> I don't know if it could help you, But maybe you could create an `phpcs.xml` then phpcs gonna take this file first.

@eerison I don't believe this is related to phpactor as I don't use it ([Intelephense](https://intelephense.com/) enabled). My question is solely about setting the coding standard for `phpcs` which is enabled by the `php` extra in LazyVim. I have a `phpcs.xml.dist` in my project and it's ignored by the extra. Either custom `phpcs.xml` files should be consulted or at minimum you need to be able to specify the coding standard. @folke any ideas? I think a lot of PHP devs are going to hit this issue because almost none of us use the exact coding standard default for `phpcs` with no modificationsl which means that any existing project we use this in is going to cause all kind of spurious diagnostics.

**Comment by eerison** [comment]
> > > Does anyone know how to configure phpcs in LazyVim to use a specific coding standard or point to a custom phpcs.xml.dist? The defaults cause a ton of problematic diagnostics in our project.
> > 
> > 
> > Hey @esetnik
> > I guess you could get support about this topic on phpactor repository https://github.com/phpactor/phpactor/discussions
> > But I didn't see an option to choose a different phpcs config :/
> > I don't know if it could help you, But maybe you could create an `phpcs.xml` then phpcs gonna take this file first.
> 
> @eerison I don't believe this is related to phpactor as I don't use it ([Intelephense](https://intelephense.com/) enabled). My question is solely about setting the coding standard for `phpcs` which is enabled by the `php` extra in LazyVim. I have a `phpcs.xml.dist` in my project and it's ignored by the extra. Either custom `phpcs.xml` files should be consulted or at minimum you need to be able to specify the coding standard. @folke any ideas? I think a lot of PHP devs are going to hit this issue because almost none of us use the exact coding standard default for `phpcs` with no modificationsl which means that any existing project we use this in is going to cause all kind of spurious diagnostics.
> 
> Edit: According to the `phpcs` documentation https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#using-a-default-configuration-file `phpcs.xml.dist` should be detected and used automatically. However, it appears that this is not working correctly with `none-ls` builtin https://github.com/nvimtools/none-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics/phpcs.lua
> 
> Edit 2: Actually it is working if I move the `.phpcs.xml` file to the root of my project. So it appears that something is wrong with the `none-ls` configuration such that it is not correctly traversing the parent directories of the current file when searching for a phpcs configuration.

Ahhh I see, I thought you are using phpactor

**Comment by esetnik** [comment]
I was able to solve the issue by specifying a custom coding standard:

```lua
  {
    "nvimtools/none-ls.nvim",
    optional = true,
    opts = function(_, opts)
      local nls = require("null-ls")
      opts.sources = opts.sources or {}
      table.insert(
        opts.sources,
        nls.builtins.formatting.phpcsfixer.with({
          extra_args = { "--rules=@PSR12" },
        })
      )
      table.insert(
        opts.sources,
        nls.builtins.diagnostics.phpcs.with({
          extra_args = { "--standard=PSR12" },
        })
      )
    end,
  },
  {
    "mfussenegger/nvim-lint",
    optional = true,
    opts = function(_, opts)
      local phpcs = require("lint").linters.phpcs

      table.insert(phpcs.args, "--standard=PSR12")

      return {
        linters_by_ft = {
          php = { "phpcs" },
        },
      }
    end,
  },
```

**Comment by esetnik** [comment]
for conform I guess we would need something like:

```lua
  {
    "stevearc/conform.nvim",
    optional = true,
    opts = function(_, opts)
      require("conform").formatters.php_cs_fixer = {
        prepend_args = { "--rules=@PSR12" },
      }

      return {
        formatters_by_ft = {
          php = { "php_cs_fixer" },
        },
      }
    end,
  },
```

**Pull request merged**
