### PR TITLE
style(dashboard): remove unnecessary brackets from keys, including extras

### PR DESCRIPTION
**Pull request by abeldekat**
Referencing this [PR](https://github.com/LazyVim/LazyVim/pull/1791)

@folke,

The p from extras.util.project still contained the brackets.

### CODE REVIEW

**Comment by minusfive** [comment]
Woops! Thanks! I think I had it on my personal config as well so that was ultimately overriding everything and missed this. Sorry about that.

**Comment by folke** [comment]
Maybe better not to override config and just fix it in project extra?
Otherwise people can't just override ops anymore

**Comment by abeldekat** [comment]
Done. Now changed in project extra.

**Comment by folke** [comment]
Thanks!

**Pull request merged**
