### PR TITLE
feat: add swift lang plugin

### PR DESCRIPTION
**Pull request by lbennett-stacki**
Extras plugin support for Swift lang

Docs: https://github.com/LazyVim/lazyvim.github.io/pull/87

https://github.com/LazyVim/LazyVim/assets/5678671/d35f127f-fb2d-4462-941d-c15f414d9ee2

## Waiting on

- [X] mason-registry swiftlint - [PR](https://github.com/mason-org/mason-registry/pull/5663)
- [X] mason-registry SwiftFormat [PR](https://github.com/mason-org/mason-registry/pull/6011)
- [ ] mason-registry xcode-build-server - [PR](https://github.com/mason-org/mason-registry/pull/6987)
- [ ] mason-registry xcbeautify - [PR](https://github.com/mason-org/mason-registry/pull/6988)

### CODE REVIEW

**Comment by lbennett-stacki** [comment]
Soooo much better than xcode 🙏 Still space for more optionals like the debugger but I'll get around to that in a later update, might take a bit longer

**Comment by Conarius** [comment]
I would wait until all the tools are available in the mason-registry.
If you want I can try to make prs for that as I somewhat regularly contribute to it

**Comment by lbennett-stacki** [comment]
I made a start over at https://github.com/mason-org/mason-registry/pull/5663

**Comment by Conarius** [comment]
There could also be the solution to use the make install command when it's installed and/or loaded as a shortcut instead of merging everything into mason

**Comment by Conarius** [comment]
@gacallea
There was a PR and it's now merged into the mason registry. Maybe you can look to other things where there isn't a PR for already.
Still thanks!

**Comment by gacallea** [comment]
@Conarius oooooopppppsss........ 😆

**Comment by lbennett-stacki** [comment]
I added a list of mason-registry dependencies merged/awaiting to the PR description

**Comment by lbennett-stacki** [comment]
and finally one for xcbeautify. Will push this on when those are merged over at mason-registry

**Comment by folke** [comment]
I'll close this for now. Let me know when it's ready with your upstream changes

**Comment by mattarau** [comment]
Hi @lbennett-stacki! Just a heads up that there was a change request in your PR: https://github.com/mason-org/mason-registry/pull/6987

**Comment by guzman109** [comment]
I have made the following PRs to Mason,

SwiftLint: https://github.com/mason-org/mason-registry/pull/12960
SwiftFormat: https://github.com/mason-org/mason-registry/pull/12961
Pymobiledevice3: https://github.com/mason-org/mason-registry/pull/12962
Xcode-build-server: https://github.com/mason-org/mason-registry/pull/12963
Xcodegen: https://github.com/mason-org/mason-registry/pull/12964
XcodeprojectCLI: https://github.com/mason-org/mason-registry/pull/12965

[Xcodebuild.nvim](https://github.com/wojciech-kulik/xcodebuild.nvim) now supports Snacks for previews.
```vim
return {
  "wojciech-kulik/xcodebuild.nvim",
  dependencies = {
    -- Uncomment a picker that you want to use, snacks.nvim might be additionally 
    -- useful to show previews and failing snapshots.

    -- You must select at least one:
    -- "nvim-telescope/telescope.nvim",
    -- "ibhagwan/fzf-lua",
    -- "folke/snacks.nvim", -- (optional) to show previews

    "MunifTanjim/nui.nvim",
    "nvim-tree/nvim-tree.lua", -- (optional) to manage project files
    "stevearc/oil.nvim", -- (optional) to manage project files
    "nvim-treesitter/nvim-treesitter", -- (optional) for Quick tests support (required Swift parser)
  },
  config = function()
    require("xcodebuild").setup({
        -- put some options here or leave it empty to use default settings
    })
  end,
}
```

**Comment by guzman109** [comment]
Question: Should there be one for Swift that supports (Linting, Formatting, Treesitter) which can be used for server side Swift and one for iOS/SwiftUI development as extras?

**Comment by Conarius** [comment]
> Question: Should there be one for Swift that supports (Linting, Formatting, Treesitter) which can be used for server side Swift and one for iOS/SwiftUI development as extras?

I think it should be split, though all the XCode stuff should also be put into the Swift extra as well. And the Swift extra as a dependency for the iOS/SwiftUI dev extra of course.

**Comment by guzman109** [comment]
The creator of XCodeBuild.nvim has a great guide to setup NeoVim for Swift and iOS programming. The only downside is the need of sudo for one of the components.

Xtool seems promising but still early in development.

**Pull request closed without merging**
