### PR TITLE
feat(extras): added zsh support

### PR DESCRIPTION
**Pull request by muneebusmani**
Added support for  diagnostics, formatting and lsp support in zsh scripts

### CODE REVIEW

**Comment by dotfrag** [comment]
I believe `beautysh` is outdated and not used by many. `shfmt` has taken over and is already in LazyVim.

**Comment by folke** [comment]
bashls also doesn't support zsh, so this extra doesn't really provide anything.
Thank you anyway! Closing

**Comment by muneebusmani** [comment]
@folke ik it doesn't support but I configured it to work on zsh files, and I get completions for most things which are common in bash and zsh

**Comment by folke** [comment]
See https://github.com/bash-lsp/bash-language-server/issues/252

**Pull request closed without merging**
