### PR TITLE
feat(core)!: move a bunch of LazyVim features to snacks.nvim

### PR DESCRIPTION
**Pull request by folke**
## Description

LazyVim comes with a bunch of smaller QoL plugin like features, but it's not easy for non LazyVim users to use them.

That's why I started working on [snacks.nvim](https://github.com/folke/snacks.nvim), a collection of small QoL plugins for Neovim.

Snacks also includes a bunch of new improvements to these features.

This PR fully integrates with snacks.

## Todo

- [ ] add proper deprecations where needed
- [ ] create snacks docs
- [ ] document all the new improvements relevant to LazyVim users

## Closes

- [ ] #4492 
- [ ] #4333
- [ ] #4687

## Checklist

- [ ] I've read the [CONTRIBUTING](https://github.com/LazyVim/LazyVim/blob/main/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by dotfrag** [comment]
Thank you, this is amazing and very welcome. I'm checked out on the branch and trying to test as many changes as I can.

**Comment by dotfrag** [comment]
Here is one..

Since you are still working on snacks, let me know if you prefer to report these after you've finished working on it.

In smaller windows, notify win width causes unwanted wrapping. Not sure if possible to wrap on whole words.

nvim-notify vs snacks notify:

2024-11-05T22:02:02,091860457+02:00
2024-11-05T22:02:15,104205791+02:00

**Comment by folke** [comment]
I think I fixed that recently. You can also get the nvim-nofity style for notifications btw (it's called `fancy`).
Make sure to update all plugins every 10 minutes or so, since I'm still working on all the things :)

**Comment by folke** [comment]
Right, you actually have a very small screen so the wrapping is indeed to be expected.
You can change the default settings for snacks.notifier:

```lua
  width = { min = 40, max = 0.4 },
  height = { min = 1, max = 0.6 },
```

**Comment by dpetka2001** [comment]
@folke I saw that you have `notifier` disabled in LazyVim and that `noice.nvim` has default notifier from snacks if it's available. So, should these settings be changed here in the plugin spec of snacks or in noice?

**Comment by folke** [comment]
@dpetka2001 you should be able to put this somewhere:

```lua
  {
    "folke/snacks.nvim",
    opts = {
      notifier = {
        width = { min = 40, max = 0.4 },
        height = { min = 1, max = 0.6 },
      },
    },
  },
```

I'm working on the install / configure docs right now, so more info soon.

**Comment by dpetka2001** [comment]
No problem. No need to reply right away. Whenever you have some free time. 

I just asked because I saw this in `lazyvim/plugins/init.lua` on line 34: `notifier = { enabled = not LazyVim.has("noice.nvim") },`, so I assumed that you have it disabled in LazyVim because Noice will already use it. So, I was wondering if the options would still take effect regardless of it being disabled or if it should be configured somewhere in Noice maybe.

**Comment by folke** [comment]
That `enabled` only causes snacks `setup` to set `vim.notify`, but for Noice users thats not needed, since noice is actually `vim.notify` and then routes stuff to `snacks`. All config options should still work as if not using noice.

**Comment by echasnovski** [comment]
screenshot_2024-11-06_10:26:58

I believe reading 'CONTRIBUTING.md' is a must for this PR to get merged. Otherwise LGTM! </s>

Jokes aside, after quick skimming I've noticed that there are a lot of `Snacks.notify()` calls. Maybe it will be better to use `vim.notify()` instead?

**Comment by folke** [comment]
@echasnovski haha :)

`Snacks.notify` is a simple wrapper to call `vim.notify`, so those will all use the installed `vim.notify`, not `Snacks.notifier`.

Will all work perfectly fine with `mini-notify` as well :)

**Comment by folke** [comment]
@echasnovski one **BIG** todo however is to rename `snacks.nvim` to `tiny.nvim`

**Comment by echasnovski** [comment]
> `Snacks.notify` is a simple wrapper to call `vim.notify`, so those will all use the installed `vim.notify`, not `Snacks.notifier`.
> 
> Will all work perfectly fine with `mini-notify` as well :)

Ah, ok, sorry. Didn't take a close enough look.

> @echasnovski one **BIG** todo however is to rename `snacks.nvim` to `tiny.nvim`

That would be enough for a lawsuit :judge: Probably not very successful one, but still...

**Comment by echasnovski** [comment]
I didn't know that supporting LSP renaming requests can be so concise. Very nice!
Then I also realized that it uses Neovim>=0.10 methods ([this](https://github.com/folke/snacks.nvim/blob/9341f730d9a6404e0b6846d38a203f40d59d0e84/lua/snacks/rename.lua#L53) and [this](https://github.com/folke/snacks.nvim/blob/9341f730d9a6404e0b6846d38a203f40d59d0e84/lua/snacks/rename.lua#L68)) and making it Neovim<=0.9 compatible will make it more verbose. But still might think about adding it to 'mini.files' directly or to 'mini.extra'; especially since it is (hopefully) similar for create and delete requests.

**Comment by dpetka2001** [comment]
`wrap` is not enabled by default any more, that's why.

**Comment by dotfrag** [comment]
I think `width` and `height` are not passed from `lazygit` to `win`:

This is what I'm trying:

```lua
map("n", "<A-g>", function() Snacks.lazygit({ width = 1, height = 1 , cwd = LazyVim.root.git() }) end, { desc = "Lazygit (Root Dir)" })
```

Also I believe we can no longer do full screen windows? The following bugs out (faded background, no foreground):

```lua

Snacks.win({
  file = vim.api.nvim_get_runtime_file("doc/news.txt", false)[1],
  width = 1, -- 0.99 works but looks a bit awkward
  height = 1, -- 0.99 works but looks a bit awkward
  wo = {
    spell = false,
    wrap = false,
    signcolumn = "yes",
    statuscolumn = " ",
    conceallevel = 3,
  },
})
```

**Comment by dpetka2001** [comment]
@dotfrag This worked for me `Snacks.lazygit({ win = { width = 0, height = 0 }, cwd = LazyVim.root.git() })`

**Comment by dpetka2001** [comment]
@dotfrag It passes the `opts` to `snacks.terminal` and if you look at `terminal.lua`, it takes options for the window config under the [win property](https://github.com/folke/snacks.nvim/blob/e78b8ae620567b645bb19ebf41a03922d001efdf/lua/snacks/terminal.lua#L12).

**Comment by dotfrag** [comment]
> @dotfrag It passes the `opts` to `snacks.terminal` and if you look at `terminal.lua`, it takes options for the window config under the [win property](https://github.com/folke/snacks.nvim/blob/e78b8ae620567b645bb19ebf41a03922d001efdf/lua/snacks/terminal.lua#L12).

You read my mind.. I was trying to figure out, thanks :sweat_smile: 

Didn't mean to clutter the PR convo, sorry.

**Comment by dpetka2001** [comment]
Yes, we shouldn't clutter this (myself included). Please open a discussion for whatever other questions you might have and I'll do my best to reply (still trying to get used to it myself and reading through the code to understand what should be done). And if I can't help you, we might ping Folke for further insight :smile:

**Comment by folke** [comment]
Just pushed a bunch of changes that should deal with deprecated functions / modules, without breaking user's configs.
Most things should be covered I think...

Will merge this soon. Need to add news first.

**Comment by folke** [comment]
Merged! :)

Will wait till tomorrow to make a new release.

**Pull request merged**
