### PR TITLE
feat: add kotlin language support with basic features

### PR DESCRIPTION
**Pull request by Dogacel**
I am pretty new to nvim toolchain. I have initially invested some time to setup a very basic kotlin config.

I would like to provide it here as a starting point.

### CODE REVIEW

**Comment by dpetka2001** [comment]
There is also #2890. But in my opinion, your handling of nvim-treesitter and mason `opts.ensured_installed` is preferred. If you could also provide linting, formatting and dap configuration (according to the official [docs](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#kotlin), because the other PR doesn't actually provide a dap configuration for Kotlin) with `optional = true` for the corresponding plugins, I think your PR would be ready to merge. 

I'm just a regular user like you, so I don't know if you should collaborate with the OP of the other PR, so that there won't be duplicate PRs for the same thing. Surely the maintainer would be more appropriate to make that decision.

**Comment by Dogacel** [comment]
@dpetka2001 Oops I actually didn't see that PR :).

Our plugins looks pretty much alike. Can you explain this? I couldn't see any difference other than semantics. Technically those arrays should be merged resulting in the same result?
> your handling of nvim-treesitter and mason opts.ensured_installed is preferred

cc @arthur-mountain if you wanna collab

**Comment by dpetka2001** [comment]
nvim-treesitter and mason's `opts.ensure_installed` are list-like tables, not key-values-like tables, so the `opts` couldn't merge them (as they use `vim.tbl_deep_extend` in the background), so they would overwrite the default `opts.ensure_installed` of those plugins and that could lead to potential issues. So, `vim.list_extend` should be used instead to append them to the original `opts.ensure_installed`.

**Comment by Dogacel** [comment]
> nvim-treesitter and mason's `opts.ensure_installed` are list-like tables, not key-values-like tables, so the `opts` couldn't merge them (as they use `vim.tbl_deep_extend` in the background, not really but a custom implementation in the `lazy.nvim` package manager that acts similarly), so they would overwrite the default `opts.ensure_installed` of those plugins and that could lead to potential issues. So, `vim.list_extend` should be used instead to append them to the original `opts.ensure_installed` of those plugins.

Very impressive, thanks for the explanation 🙇

**Comment by dpetka2001** [comment]
Not impressive, i'm not even a programmer. And if you ask me about technical details i doubt i could answer you. It's just basic knowledge of Lua i aqcuired to be able to understand at least on the surface how i can configure my Neovim. I just tried examples of code and printed them out so i could see what they produce in order to be able to visualize what's happening (for example i tried a variant of mason's `ensure_installed` and tried to extend both with `vim.tbl_deep_extend` and `vim.list_extend` and saw the results for myself) . That's all :p

**Comment by arthur-mountain** [comment]
@dpetka2001

Oh, I didn't realize `opts.ensured_installed` would overwrite; 

I thought it would merge. Otherwise, I would have updated the reference via a function.

**Comment by arthur-mountain** [comment]
@Dogacel 
> Our plugins looks pretty much alike. Can you explain this? I couldn't see any difference other than semantics. Technically those arrays should be merged resulting in the same result?

I'm about to start learning Kotlin, but I found out that lazyvim doesn't support Kotlin.

I searched through the issues and found [this one](https://github.com/LazyVim/LazyVim/issues/2546) that was closed, but it seems there hasn't been any follow-up pull request.

So, I'm trying to provide the kotlin support.

Our plugins seem to be the same, except for the above, I might accidentally overwrite opts.ensured_installed >__<

**Comment by arthur-mountain** [comment]
@Dogacel 
I'm sorry. What should I do in such a situation?

This is my first time contributing a PR.

I will also update my PR to avoid overwriting ensured_installed.

**Comment by Dogacel** [comment]
> @Dogacel I'm sorry.>__<
> 
> What should I do in such a situation?
> 
> This is my first time contributing a PR.
> 
> I will also update my PR to avoid overwriting ensured_installed.

I want to say you opened the PR first and I missed it, so it would be better if you update your PR with the approach I did and we can continue from there. 🙂

**Comment by arthur-mountain** [comment]
@Dogacel 
> I want to say you opened the PR first and I missed it, so it would be better if you update your PR with the approach I did and we can continue from there. 🙂

Thank you very much for your kindness and warmth.

I have made the following changes and updates on GitHub:
1. Updated settings for `mason` and `nvim-treesitter` to avoid overriding ensure_installed.
2. Added DAP configuration.

**Pull request closed without merging**
