### PR TITLE
fix(extra-lang-angular): add BufNew event to attach angular treesitter

### PR DESCRIPTION
**Pull request by mishasbtr**
## Problem

Sometimes angular treesitter didn't get started, e.g. when creating a new file.

## Solution

- Add `BufNew` event to attach angular treesitter.
- Change `BufRead` to `BufReadPost` for better readability.

### Related Neovim docs
- [BufRead / BufReadPost docs](https://neovim.io/doc/user/autocmd.html#BufRead)
- [BufNew](https://neovim.io/doc/user/autocmd.html#BufNew)

### CODE REVIEW

**Comment by folke** [comment]
Sorry, but that's not a good solution for this, since this will restart treesitter highlighting whenever you enter the buffer

**Comment by dpetka2001** [comment]
@mishasbtr Have you tried using `{ "BufReadPost", "BufNewFile" }` instead? `BufReadPost` is the same as `BufRead`, I'm just used to it as I can distinguish it easier versus `BufReadPre`.

**Comment by mishasbtr** [comment]
> @mishasbtr Have you tried using `{ "BufReadPost", "BufNewFile" }` instead? `BufReadPost` is the same as `BufRead`, I'm just used to it as I can distinguish it easier versus `BufReadPre`.

@dpetka2001 this seems like a good solution, will try and test it out

**Comment by mishasbtr** [comment]
@dpetka2001 thank you for your suggestion, it worked out very well :+1:

**Comment by mishasbtr** [comment]
> Sorry, but that's not a good solution for this, since this will restart treesitter highlighting whenever you enter the buffer

@folke updated the implementation suggested by @dpetka2001 to include an additional `BufEnter ` event for attaching treesitter

**Pull request merged**
