### PR TITLE
LazyVim 10.0

### PR DESCRIPTION
**Pull request by folke**
# Todo

- [x] split `lazyvim.util` in multiple smaller modules for better readability and performance
  * existing `lazyvim.util` functions can still be used, and a deprecation warning will be shown
- [x] new formatting framework that specs can use to integrate formatters / linters with fixers
  * a formatter can be `primary` 
  * only one `primary` formatter will run based on availability and `priority`
  * secondary formatters will always run when available (like eslint fixes)
  * Added `:LazyFormat` and `:LazyFormatInfo` commands
 - [x] make conform/nvim-lint the default and have none-ls as an extra
 - [x] make `dashboard.nvim` the default instead of `alpha.nvim`. Better code and better performance
 - [x] customizable root detection and `:LazyRoot`
 - [x] added `:LazyExtras` to easily enable/disable LazyVim extras
 - [x] moved `nvim-navic` to extras in favor of `nvim-treesitter-context`
 - [x] add `nvim-ts-autotag` by default
 - [x] added extra for `aerial.nvim` with integrations for telescope, lualine and edgy 
 - [x] kind filter can now be configured (defaults & per file-type). Used by telescope and aerial. 
 - [x] added extra for `symbols-outline.nvim` 
 - [ ] docs on formatting, rootdir, extras, ...

## Testing

To test the new release, add the below somewhere in your specs:

```lua
    { "LazyVim/LazyVim", import = "lazyvim.plugins" }, -- keep this separate as you have it already in your config
    { "LazyVim/LazyVim", branch = "refactor", version = false }, -- add this new entry below
```

## `:LazyExtras`

image

## `:LazyRoot`

image

## `:LazyFormatInfo`

image

Fixes #1666

### CODE REVIEW

**Comment by javlocan** [comment]
Hi! I'm kind of new in both development (web, aggg) and neovim, but I'm a huge fan. I don't really know how I can help. 
For the time being I will 'install' (don't know the appropriate term here) and report any bug or issue I could find that after research I can't relate to a plugin thing.

Keep the good work! Your plugin manager is my fav. Cheers.

**Comment by abusch** [comment]
I gave it a try and enabled the `aerial` extra, which seems to have added a `<leader>cs` mapping to `<cmd>SymbolsOutline` but there doesn't seem to be any such command... should it be mapped to `AerialToggle` instead?

**Comment by folke** [comment]
@abusch right, will fix! And also need to add that extra for symbols outline.

**Comment by lkhphuc** [comment]
>     { "LazyVim/LazyVim", import="lazyvim.plugins", branch = 'refactor', version = "10.x" },

Not sure if this changes or not, but I still need to import default plugins or else it doesn't work

**Comment by folke** [comment]
@lkhphuc you need to specify `version = false` for it to work as specified in the PR description.
Version `10.x` has not been released yet.

**Comment by lkhphuc** [comment]
Ah thanks. It automatically updated correctly now.


Not a big deal since I can fix these in my config, but since you asked to report any error beside the deprecation warning:

```
   Error  09:56:26 notify.error lazy.nvim Failed to load `plugins.none-ls`

/Users/plekhac/.config/nvim/lua/plugins/none-ls.lua:5: module 'null-ls' not found:
	no field package.preload['null-ls']
cache_loader: module null-ls not found
cache_loader_lib: module null-ls not found
	no file './null-ls.lua'
	no file '/opt/homebrew/share/luajit-2.1.0-beta3/null-ls.lua'
...
```
From my old null-ls config, migrating/delete null-ls for now fixes it.

```
   Error  09:56:26 notify.error lazy.nvim Two plugins with the same name and different url:
{
  new = { "romgrk/nvim-treesitter-context",
    _ = {
      dep = false,
      fid = 150,
      fpid = 148,
      module = "plugins.treesitter"
    },
    dir = "/Users/plekhac/.local/share/nvim/lazy/nvim-treesitter-context",
    name = "nvim-treesitter-context",
    opts = {
      multiline_threshold = 2
    },
    url = "https://github.com/romgrk/nvim-treesitter-context.git"
  },
  old = { "nvim-treesitter/nvim-treesitter-context",
    _ = {
      dep = false,
      fid = 39,
      module = "lazyvim.plugins.treesitter"
    },
    dir = "/Users/plekhac/.local/share/nvim/lazy/nvim-treesitter-context",
    enabled = true,
    event = "LazyFile",
    name = "nvim-treesitter-context",
    opts = {
      mode = "cursor"
    },
    url = "https://github.com/nvim-treesitter/nvim-treesitter-context.git"
  }
}
```
Reinstall from new origin and update my config fixes it.

```
   Error  09:56:27 notify.error lazy.nvim Failed to run `config` for nvim-navbuddy

...share/nvim/lazy/nvim-navbuddy/lua/nvim-navbuddy/init.lua:1: module 'nvim-navic.lib' not found:
	no field package.preload['nvim-navic.lib']
cache_loader: module nvim-navic.lib not found
cache_loader_lib: module nvim-navic.lib not found
	no file './nvim-navic/lib.lua'
	no file '/opt/homebrew/share/luajit-2.1.0-beta3/nvim-navic/lib.lua'
	no file '/usr/local/share/lua/5.1/nvim-navic/lib.lua'
	no file '/usr/local/share/lua/5.1/nvim-navic/lib/init.lua'
	no file '/opt/homebrew/share/lua/5.1/nvim-navic/lib.lua'
	no file '/opt/homebrew/share/lua/5.1/nvim-navic/lib/init.lua'
	no file './nvim-navic/lib.so'
	no file '/usr/local/lib/lua/5.1/nvim-navic/lib.so'
	no file '/opt/homebrew/lib/lua/5.1/nvim-navic/lib.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './nvim-navic.so'
	no file '/usr/local/lib/lua/5.1/nvim-navic.so'
	no file '/opt/homebrew/lib/lua/5.1/nvim-navic.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - /opt/homebrew/Cellar/neovim/HEAD-c40a1c0/share/nvim/runtime/lua/vim/lsp.lua:1710 _in_ **_on_attach**
  - /opt/homebrew/Cellar/neovim/HEAD-c40a1c0/share/nvim/runtime/lua/vim/lsp.lua:1460 _in_ **fn**
  - vim/_editor.lua:341
```
Not sure about why navic was removed though.

**Comment by abusch** [comment]
@lkhphuc yeah, that's the same error I had regarding `none-ls`.

Regarding `navic`, the description mentions:
> moved nvim-navic to extras in favor of nvim-treesitter-context

**Comment by lkhphuc** [comment]
@abusch ah make senses then. But still shouldn't throws an error. A notification about enabling this extra would be nice.


Also, the stacktrace for this is a bit obscure. If it can point out to my file "nvim/lua/plugins/lsp.lua" where I specify that would be nice.
```
   Warn  10:08:52 notify.warn LazyVim `nvim-lspconfig.opts.autoformat` is deprecated. Please use `vim.g.autoformat` instead

# stacktrace:
  - vim/_editor.lua:418 _in_ **cmd**
  - /persistence.nvim/lua/persistence/init.lua:57 _in_ **load**
  - lua:1
  - vim/_editor.lua:418 _in_ **cmd**
  - /dashboard-nvim/lua/dashboard/theme/doom.lua:23
```

**Comment by lkhphuc** [comment]
Sure here is my none-ls.lua file.
```lua
return {
  "nvimtools/none-ls.nvim",
  opts = {
    sources = {
      require("null-ls").builtins.formatting.yapf.with({
        extra_args = function(params)
          return params
            and {
              "--style={indent_width:" .. vim.fn.shiftwidth() .. "}",
            }
        end,
      }),

      require("null-ls").builtins.formatting.stylua.with({
        extra_args = function(params)
          return params
            and {
              "indent-type=Spaces, indent-width=" .. vim.fn.shiftwidth(),
            }
        end,
      }),

      require("null-ls").builtins.code_actions.shellcheck,

      require("null-ls").builtins.hover.dictionary,
      require("null-ls").builtins.hover.printenv,
    },
  },
}
```

**Comment by folke** [comment]
Just added additional warning message when trying to load a lua module from a plugin that is no longer in core:
image

**Comment by folke** [comment]
@lkhphuc I see. The error is actually because your spec itself already loads `none-ls`.
So if you would remove all your plugins, then that spec would always fail.

Better to make `opts` a function so that it's in a closure and will only be called when `none-ls` is installed.

**Comment by abusch** [comment]
I still get an error if I disable the `none-ls` extra: 
image

But that seems to be because I only used "none-ls.nvim" in my spec instead of the full "nvimtools/none-ls.nvim", so that's probably my fault 😅 (although somehow it works if the plugin is there ...)

**Comment by folke** [comment]
@abusch yes, that's normal. When you use a short name for a plugin, then you need to have loaded the plugin somewhere else (by enabling the extra in this case)

**Pull request merged**
