### PR TITLE
feat(extras): added lazyvim extra for laravel blade support

### PR DESCRIPTION
**Pull request by Stephan-MC**
## Description

This pull request will be a great lift for laravel developers. It is going to 
- add a new filtype for all ```.blade.php``` 
- Add new treesitter query highlights for ```blade```
- Add treesitter query injections for ```blade```
- nvim users will now be able to use ```TSInstall blade``` to install blade.
- Added new lazyvim ```extras``` for the ```blade```
- Configures ```formatting``` with conform.nvim
- Configures ```linting``` with nvim-lint

## Related Issue(s)

[feature: lazy extra for Laravel blade and php](https://github.com/LazyVim/LazyVim/issues/3386)

## Screenshots

https://github.com/user-attachments/assets/c449a430-f989-4279-8685-a1815597d78b

## Checklist

- [x] I've read the [CONTRIBUTING](https://github.com/LazyVim/LazyVim/blob/main/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by RayGuo-ergou** [comment]
I think it's better to depends on php, like https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/plugins/extras/lang/vue.lua#L10

And I am using a plugin for laravel blade: https://github.com/ricardoramirezr/blade-nav.nvim, maybe also worth to introduce here?

**Comment by Stephan-MC** [comment]
> I think it's better to depends on php, like
> 
> https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/plugins/extras/lang/vue.lua#L10
> 
> And I am using a plugin for laravel blade: https://github.com/ricardoramirezr/blade-nav.nvim, maybe also worth to introduce here?

please tell me more about it. haven't heard or tried yet. may be it could be of great help

**Comment by Stephan-MC** [comment]
please this PR has been opened for months waiting for a pull request. some please take action @folke :1st_place_medal:

**Comment by dpetka2001** [comment]
#4553

**Comment by Stephan-MC** [comment]
Ok I’ll see if I can bring more updates for the mean time

**Comment by Conarius** [comment]
I think it would be better to remove the php treesitter and just import the php extra (cuz using blade without any php stuff would be pointless)

**Comment by folke** [comment]
Thank you for this PR, however I think before merging this, it would be better to make sure blade is officially supported by nvim-treesitter first, so best to open a PR there.

**Comment by folke** [comment]
I'll close this for now. Feel free to open a new PR once blade is part of nvim-treesitter

**Comment by muneebusmani** [comment]
@folke blade wont get into nvim-treesitter, we laravel devs have to rely on blade parsers by other people, there are repos for this as old as 3 to 4 years ago, i dont know why nvim-treesitter guys dont add this, but it would be ages till this gets official support, i suggest merging this pr as this isnt the solution.

**Comment by muneebusmani** [comment]
> Thank you for this PR, however I think before merging this, it would be better to make sure blade is officially supported by nvim-treesitter first, so best to open a PR there.

bro it will never officially become supported in treesitter-blade as it has been used via this method since ages, there may be many pending pr's in the tree-sitter repo for this laravel blade , but they never merge it, it would've been better if you reconsider it

**Comment by Stephan-MC** [comment]
> > Thank you for this PR, however I think before merging this, it would be better to make sure blade is officially supported by nvim-treesitter first, so best to open a PR there.
> 
> bro it will never officially become supported in treesitter-blade as it has been used via this method since ages, there may be many pending pr's in the tree-sitter repo for this laravel blade , but they never merge it, it would've been better if you reconsider it

that's harsh 😢. Any ways i'll keep trying.

**Comment by muneebusmani** [comment]
@Stephan-MC @folke  
blade is officially supported now by treesitter

**Comment by Stephan-MC** [comment]
OK. Will have a look at it...
thanks...

I htink having blade support now will be as easy as doing `:TSInstall blade`.

That means this PR isn't necessary anymore. 😄

**Comment by ronald2wing** [comment]
Maybe add Pint too.

**Comment by Stephan-MC** [comment]
Pint can’t be installed via `mason`

**Comment by muneebusmani** [comment]
> Pint can’t be installed via `mason`

Bruh you high or something? It is literally in mason

**Comment by muneebusmani** [comment]
> Maybe add Pint too.

Do a pr if you need that so much, nobody is getting paid to contribute, so no one is entitled to meet your demands bruh.
If you really think this stuff is necessary, then add a feature request issue, and properly express the request of the feature you want, the way you are asking is like demanding the feature, spamming same thing across all discussions, issues related to Laravel.

**Comment by ronald2wing** [comment]
> > Maybe add Pint too.
> 
> Do a pr if you need that so much, nobody is getting paid to contribute, so no one is entitled to meet your demands bruh. If you really think this stuff is necessary, then add a feature request issue, and properly express the request of the feature you want, the way you are asking is like demanding the feature, spamming same thing across all discussions, issues related to Laravel.

Yeah, I was going to, but the issue said that if it is extras-related, I will have to discuss first and have people to approve. I could use my current LazyVim Laravel setup.

**Comment by ronald2wing** [comment]
Treesitter, Pint, blade, tailwind, and a Laravel package for now. Neotest will work if PHP is installed.

**Comment by muneebusmani** [comment]
> Treesitter, Pint, blade, tailwind, and a Laravel package for now. Neotest will work if PHP is installed.

Bruh I have been constantly telling you, I am a bigger nerd of neovim than you, doing Laravel from a long time, and I am telling you that currently it is not possible  to properly get the work done for Laravel, if you are a developer and want to get the  shit done, then use phpstorm, there are many good and bad ways to get it to work for free, and it is the best ide if you are a professional, but if you are a hobbyist, and don't actually solve problems for people in Laravel, then you can try wasting as much time as you want in trying to make Laravel work In neovim, I did the same when I got into neovim ecosystem but I realized it is no hope, for now, there is currently work going on Laravel ls, it will take approx a year or 2 to be able to actually do Laravel stuff completely same as in phpstorm, otherwise try and waste you time, blade files would get treesitter and php stuff would work but blade won't get intellisense of variables injection like in phpstorm, nor would you properly get completion Laravel magic in controllers, eloquent models, migrations, etc, you can use Laravel ide helper but I can only take you so far, it won't make nvim completely understand the Laravel magic, if you still want to do it, please fo ahead and don't comment on this thread please, you have been annoying me for several days, spamming the same thing over and over and over again.

**Comment by ronald2wing** [comment]
Here is a laravel extra with blade and other Laravel features https://github.com/LazyVim/LazyVim/pull/6830

**Pull request closed without merging**
