### PR TITLE
feat(dap): add clangd debuggee launch arguments

### PR DESCRIPTION
**Pull request by genmzy**
Clang debuggee launch should be able to pass arguments, now add that

### CODE REVIEW

**Comment by folke** [comment]
I added a new keymap `<leader>da` that you can use with any dap configuration to alter the args

**Comment by fredrikaverpil** [comment]
@folke it also looks like that args are being asked about even if I don't pick the option that says `(Arguments)` in the debug window. Not sure if this is a go/delve specific issue?



https://github.com/LazyVim/LazyVim/assets/994357/4648dcfb-1beb-4413-93bb-2d1f799b1c9b

**Comment by folke** [comment]
probably a go thing indeed. The new functionality is only for the `<leader>da` keymap

**Comment by genmzy** [comment]
> I added a new keymap `<leader>da` that you can use with any dap configuration to alter the args

Good job😄

**Comment by fredrikaverpil** [comment]
> probably a go thing indeed. The new functionality is only for the `<leader>da` keymap

Yeah, but [this](https://github.com/LazyVim/LazyVim/pull/1629#issuecomment-1757678475) is not related to go, right?

**Comment by folke** [comment]
right, will move those old dap adapter mappings I made at some point. They're conflicting

**Comment by folke** [comment]
it works though, just which-key that acts up :)

**Comment by folke** [comment]
Also, I just checked and once you did the with args thing, the normal mapping also asks args. Will look into this.

**Pull request closed without merging**
