### PR TITLE
feat: add undo tree

### PR DESCRIPTION
**Pull request by rubiin**
This is the continuation of  https://github.com/LazyVim/LazyVim/pull/3148
The old pr got deleted when I deleted the main branch

### CODE REVIEW

**Comment by surmish** [comment]
Really don't think `LazyVim` should be adding this, `telescope-undo.nvim` is an option that people tend to use too. This looks like it belongs in personal config area.

**Comment by rubiin** [comment]
Yeah I was gonna go for that but this seems to be more popular among the developers

**Comment by muneebusmani** [comment]
Bruh telescope isn't everything, undotree is the goat, it can easily integrate into edgy

**Comment by surmish** [comment]
> Bruh telescope isn't everything, undotree is the goat, it can easily integrate into edgy

Telescope-undo isn't a part of LazyVim either. See the requirements for adding an extra. Straightforward configurations don't belong in an extra.

**Comment by rubiin** [comment]
If we were to add telescope-undo, I think it wont work with fzf as fzf replaces telescope. This pr is a continuation of https://github.com/LazyVim/LazyVim/pull/3148, the configurations that undotree requires was stripped down

**Comment by dpetka2001** [comment]
Honestly, in my personal opinion, this is a really straightforward configuration and neither of the plugins mentioned here should belong in a Neovim distro I believe. It would be best if users could choose whichever one they like and just install it in their personal configuration. 

If it were to make it into an Extra I would also prefer something that's not telescope related. I've fully switched into fzf-lua Extra since it got merged yesterday. Maintainer has the final say.

**Comment by kevintraver** [comment]
There is a lua version that might also be worth checking out as well: [https://github.com/jiaoshijie/undotree](https://github.com/jiaoshijie/undotree)

**Pull request closed without merging**
