### PR TITLE
feat: add a keybind to search register

### PR DESCRIPTION
**Pull request by qizidog**
use `<leader>"` to search register through telescope

### CODE REVIEW

**Comment by dpetka2001** [comment]
Isn't this more of a personal configuration? LazyVim already provides `"` to see what's in the registers.

**Comment by qizidog** [comment]
@dpetka2001  wow, I didn't notice that, anyway keybind `"` is a little hard to be found.

Just a suggestion, not bad, contemplate its adoption as you like~

**Comment by dpetka2001** [comment]
It's up to the maintainer to decide, not me. I just expressed my personal opinion. No hard feelings :smile:

**Comment by folke** [comment]
It doesn't hurt to have this keymap as well I guess :)

Merged. thank you!

**Pull request merged**
