### PR TITLE
fix(gitsigns): change name of filetype blame

### PR DESCRIPTION
**Pull request by dpetka2001**
## Description
There was a change in `gitsigns` filetype name for blame.

## Related Issue(s)
No

## Checklist

- [x] I've read the [CONTRIBUTING](https://github.com/LazyVim/LazyVim/blob/main/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by dotfrag** [comment]
Thanks - for reference: breaking change here https://github.com/lewis6991/gitsigns.nvim/commit/0ed4669

**Comment by iamxiaojianzheng** [comment]
@folke Can pay attention to this pr?

**Comment by dpetka2001** [comment]
@iamxiaojianzheng No need to rush things. Please be patient. Either way it's something that you can easy integrate into your autocmds until this gets merged.

**Comment by folke** [comment]
ty!

**Pull request merged**
