### PR TITLE
feat(toggle): add illuminate toggle for which-key

### PR DESCRIPTION
**Pull request by bitbirddev**
## Description
Adds a Toggle-Shortcut to enable/disable [Illuminate](https://github.com/RRethy/vim-illuminate)

I dont think 'leader ux' is the right shortcut here. I just took the next free one.

image

### CODE REVIEW

**Comment by bitbirddev** [comment]
@folke done! unfortunately it does no longer show up in whichkey even though the keyboard shortcut <leader>ux is working...

**Comment by dpetka2001** [comment]
You didn't rebase your branch to pull the latest changes. You're still on 12.44.1, so `snacks.nvim` is not installed.

**Comment by bitbirddev** [comment]
@dpetka2001 should be up to date now

**Comment by folke** [comment]
ty!

**Comment by bitbirddev** [comment]
any idea why the keymap doesn't show up in whichkey anymore?

**Comment by dpetka2001** [comment]
It shows up correctly for me. Maybe something in your personal configuration?

**Comment by bitbirddev** [comment]
@dpetka2001 thank you! will investigate on my side!

**Pull request merged**
