### PR TITLE
feat(telescope): add `<leader>fR` for `:Telescope resume`

### PR DESCRIPTION
**Pull request by cbochs**
I've recently switched to LazyVim and really liked many of the out-of-the-box defaults. One keybind I would like though is a way to quickly call `Telescope resume`. I thought `<leader>fR` might be a good place for it. Let me know what you think.

Thanks!

### CODE REVIEW

**Comment by alezunino** [comment]
I use <leader>sR for :Telescope resume because there are are many Telescope keys under "<leader>s"

**Comment by cbochs** [comment]
Fair. I'm happy to move it under the `<leader>s` (search) category instead.

**Comment by alezunino** [comment]
I have this in keymaps.lua:
`
vim.keymap.set("n", "<leader>sR", "<cmd>Telescope resume<cr>", { desc = "Resume telescope search" })
`

**Comment by folke** [comment]
`sR` probably makes more sense indeed.

**Comment by folke** [comment]
Thank you!

**Pull request merged**
