### PR TITLE
refactor(cmp): add `optional` where necessary

### PR DESCRIPTION
**Pull request by dpetka2001**
## Description
Makes it easier to disable it for users who want to try other completion engines, without it being pulled back by some Extra.

## Related Issue(s)
None

## Checklist

- [x] I've read the [CONTRIBUTING](https://github.com/LazyVim/LazyVim/blob/main/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by idelice** [comment]
Shouldn't this PR also apply optional capabilities for nvim-jdtls in some way?

https://github.com/LazyVim/LazyVim/blob/13a4a84e3485a36e64055365665a45dc82b6bf71/lua/lazyvim/plugins/extras/lang/java.lua#L169

**Comment by dpetka2001** [comment]
`LazyVim.has("cmp-nvim-lsp")` checks if `cmp-nvim-lsp` exists. If it exists it adds to capabilities, otherwise it's nil.

**Comment by idelice** [comment]
> `LazyVim.has("cmp-nvim-lsp")` checks if `cmp-nvim-lsp` exists. If it exists it adds to capabilities, otherwise it's nil.

I know, but what if you want to add other capabilities?

**Comment by dpetka2001** [comment]
I don't do Java, so can't test this. My guess would be to also expose capabilities in `opts` and then in the local `config` do something like what is being done [here](https://github.com/LazyVim/LazyVim/blob/13a4a84e3485a36e64055365665a45dc82b6bf71/lua/lazyvim/plugins/lsp/init.lua#L187-L193) to merge all the capabilities together. 

One who does Java should make an appropriate PR after having it tested thoroughly.

**Comment by folke** [comment]
ty!

**Pull request merged**
