### PR TITLE
feat(util) create gitui extension

### PR DESCRIPTION
**Pull request by appelgriebsch**

### CODE REVIEW

**Comment by sqwxl** [comment]
I've found lazygit to be slow and buggy, but still useful in some cases. gitui seems like a worthwhile alternative.

**Comment by appelgriebsch** [comment]
Yeah, also was surprised to see that they have the gitui binary as part of mason registry, which makes installing/updating it a snap...

**Comment by neuromaancer** [comment]
Unfortunately, I just copy and paste the code, it doesn't work for me when I click <leader>gg. It doesn't start properly, there seems to be a window, but it flashes back.

**Comment by neuromaancer** [comment]
Yeah, I am sure.

**Comment by dpetka2001** [comment]
Strange, it works for me.

**Comment by neuromaancer** [comment]
There are two things to verified:

1.did you use edgy.nvim? I think it might affect the window layout.

2. I only installed the gitui but not by external tool for example: homebrew. I don't know if this will cause it?

**Comment by dpetka2001** [comment]
I don't use edgy and I just used the code in this PR to install `gitui` via Mason.

**Comment by neuromaancer** [comment]
Okay, I have figured out why. I need to first uninstall edgy and install `gitui`, lastly reinstall edgy. I think edgy does something for the registered window app, but if it is new installed one. It might flash back.

**Comment by folke** [comment]
Thanks!

**Pull request merged**
