### PR TITLE
fix(lazygit): improve git browse

### LINKED ISSUE #3886: bug:  <leader>gB (git browse) doesn't handle correctly azure devops remotes
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

NixOS

### Describe the bug

Git repository url isn't computed correctly for azure devops git remote when using the builtin keymap `<leader>gB`.

I checked [vim-fugitive](https://github.com/tpope/vim-fugitive), and they seem to offload this task to other plugins to implement the logic needed for the mapping (git remote url to repo website url). Example [fugitive-azure-devops.vim](https://github.com/cedarbaum/fugitive-azure-devops.vim)

Also I checked [neogit](https://github.com/NeogitOrg/neogit), and they have a simpler solution using templates; they use this for open pull request, but it can be used also for browse branch.
https://github.com/NeogitOrg/neogit/blob/66b29453df7050543a51986620f8961a79a13fcc/lua/neogit/config.lua#L323-L327
```lua
    git_services = {
      ["github.com"] = "https://github.com/${owner}/${repository}/compare/${branch_name}?expand=1",
      ["bitbucket.org"] = "https://bitbucket.org/${owner}/${repository}/pull-requests/new?source=${branch_name}&t=1",
      ["gitlab.com"] = "https://gitlab.com/${owner}/${repository}/merge_requests/new?merge_request[source_branch]=${branch_name}",
      ["azure.com"] = "https://dev.azure.com/${owner}/_git/${repository}/pullrequestcreate?sourceRef=${branch_name}&targetRef=${target}",
```

### Steps To Reproduce

On an azure devops git repo, in normal mode click `<leader>gB` leads to 404 page on your browser

### Expected Behavior

The correct repo url should be computed depending on the git remote provider

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### PR DESCRIPTION
**Pull request by med8bra**
## Description
Improves git browse command by handling different types of remotes, and allows user to extend to other git hosts.

## Related Issue(s)
Fixes #3886

## Checklist
- [x] I've read the [CONTRIBUTING](https://github.com/LazyVim/LazyVim/blob/main/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by folke** [comment]
fyi, I'm working on this PR. Will push in a bit :)

**Comment by folke** [comment]
I've refactored the code and changed it use simple replacement patterns to get the final url.
I've also extended your tests for a lot of existing git providers.

Would be great if you could review and when done, I can merge this...

**Comment by rbhanot4739** [comment]
@folke Sorry for hijacking and commenting on this but this seems to not work correctly for me. This is how my remote looks
```
origin  ssh://org-127256988@github.com/<org_name>/repo_name (fetch)
origin  ssh://org-127256988@github.com/<org_name>/repo_name (push)
```

And when I press `<leader>gB` it simply appends the `https://` to the origin name and does not seem to replace the `ssh://org-127256988@`. Here is the lazyvim log line
```
Info  16:04:08 notify.info LazyVim Opening [origin](https://ssh://org-127256988@github.com/<org_name>/repo_name)
```
Do I need to something to make this work ?

**Comment by dpetka2001** [comment]
Your pattern doesn't seem to be supported in the current patterns mentioned [here](https://github.com/LazyVim/LazyVim/blob/13a4a84e3485a36e64055365665a45dc82b6bf71/lua/lazyvim/util/lazygit.lua#L167-L178). It seems to only support patterns of `ssh://git@something` and `ssh.dev.azure` at the moment.

If you like submit a PR for your pattern to be included.

**Comment by dpetka2001** [comment]
@folke I worked on a adding a feature to make the `remote_patterns` extensible by the user from his own configuration. I don't really know if something like this is desirable. I just thought it would be good to avoid future PRs for including a single line pattern in `remote_patterns`, but maybe you're ok with such PRs, so it doesn't matter in that case.

The branch I worked on, you can take a look [here](https://github.com/LazyVim/LazyVim/compare/main...dpetka2001:LazyVim:feat/lazygit_new_pattern). 

I added the function `dedup_list_tbl` to deduplicate entries from lists that contain tables as elements. I tried to implement that in the current `LazyVim.dedup` function but the print results from my testing showed weird results, so I decided to make it a different function (for my  own convenience, but if you can incorporate it into current `LazyVim.dedup` please feel free). 

The deduplication is needed (from my own testing at least and of course I might be wrong in the way I did it), because if a repo has more than one remote then appending `vim.g.lazygit_remote_patterns` to `M.remote_patterns` creates duplicate entries for each remote.

If you would like me to create the PR just say so, I just refrained from creating one because I'm not sure if such a behavior is something you desire and I don't want to spam PRs.

I did the merging of the lists inside `get_url` function because if I put it outside like `M.remote_patterns` is already then the table seems to get evaluated during the parsing phase of `lazy.nvim` (although I'm not sure about that) and the merging of the lists doesn't take place in time (at least those were the results from the printing of `M.remote_patterns` that I did to verify if the 2 lists got merged).

**Pull request merged**
