### PR TITLE
feat(lang): add telescope terraform integrations

### LINKED ISSUE #2234: feature: add `cappyzawa/telescope-terraform.nvim` and `ANGkeith/telescope-terraform-doc.nvim` to `lazyvim.plugins.extras.lang.terraform`
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

`cappyzawa/telescope-terraform.nvim` provides information about terraform modules, resources, & data through Telescope.

`ANGkeith/telescope-terraform-doc.nvim` provides terraform documentation information through Telescope

### Describe the solution you'd like

Enabling `lazyvim.plugins.extras.lang.terraform` should automatically setup these telescope extensions 

### Describe alternatives you've considered

Overriding telescope plugin to manually setup additional extensions.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pbnj**
Closes #2234

Add telescope integrations for:

- https://github.com/ANGkeith/telescope-terraform-doc.nvim
- https://github.com/cappyzawa/telescope-terraform.nvim

### CODE REVIEW

**Comment by dpetka2001** [comment]
Is there a reason you load both these plugins in `VeryLazy`? Since they will load either way with Telescope, I don't believe it is necessary. And less plugins loading at startup.

**Comment by pbnj-dragon** [comment]
@dpetka2001 - thank you for the feedback.

> Is there a reason you load both these plugins in VeryLazy? 

I copied existing patterns in other Extras that setup telescope extensions, like `extras/util/project.lua`.

Nonetheless, I removed `event = "VeryLazy"`.

**Comment by pbnj** [comment]
@dpetka2001 - thank you for the feedback.

> Is there a reason you load both these plugins in VeryLazy? 

I copied existing patterns in other Extras that setup telescope extensions, like `extras/util/project.lua`.

Nonetheless, I removed `event = "VeryLazy"`.

**Comment by dpetka2001** [comment]
Oh I don't use that and hadn't noticed. I think the removal shouldn't affect anything. I checked out your PR locally and removing those events didn't seem to affect anything. Of course, I'm just a user like you and also don't know anything about Terraform, that's why I asked if you noticed any problems. 
With the removal of the events, Telescope pickers still seemed to work fine for these 2 plugins. 
If you do notice that something is amiss, regarding functionality of the plugins, feel free to add them back. 
But from my observations, it didn't seem to cause any wrong to have them lazy-loaded along Telescope.

**Comment by pbnj** [comment]
I agree. I don't think lazy loading Telescope extensions are necessary.

In my previous (lazy.nvim) setup, I loaded the extensions along with Telescope.

**Comment by pbnj** [comment]
I question if they should be `optional = true`.

If so, how do users opt-in or opt-out of these extensions?

**Comment by dpetka2001** [comment]
`optional` is not for users to opt in or out of plugins. To quote from `lazy.nvim`'s docs
> When a spec is tagged optional, it will only be included in the final spec, when the same plugin has been specified at least once somewhere else without optional. This is mainly useful for Neovim distros, to allow setting options on plugins that may/may not be part of the user's plugins

So, for example there is the `extras.dap.core` which provides the core functionality for DAP config in LazyVim. And then in the `extras.lang.*`, you will see that `nvim-dap` is specified with `optional = true`. That essentially means that if you enable the language extra and you don't have the core dap enabled, that part of the dap spec in the language extra won't get added in the user's configuration.
If a user that enables the `extras.lang.terraform` would like to not have these 2 plugins, he would have to explicitly disable them in his own personal configuration.

**Comment by pbnj** [comment]
Makes sense. Thank you for clarifying.

**Comment by folke** [comment]
Thanks!

**Pull request merged**
