### PR TITLE
Fixing telescope find files keymaps.

### PR DESCRIPTION
**Pull request by ckt114**
Fixing telescope find files keymaps that seems to be mixed up.

### CODE REVIEW

**Comment by dpetka2001** [comment]
They're not mixed up. By default, in `Util.telescope` `cwd` is set to `Util.root`, which searches in `root_dir`. If you set `cwd = false`, then it defaults to `vim.loop.cwd` and searches in current working directory.

**Comment by ckt114** [comment]
Could you please try those keys again? When I open a file in subfolders of a git repo and do `<leader><space>` the first time it works correctly but when I did that again it only showed files in the folder when the current file is opened.

**Comment by dpetka2001** [comment]
Do you happen to have some kind of patterns in your subfolders that are being considered by LSP? What does `:LazyRoot` tell you? It sounds to me like LSP misconfiguration. I will check tomorrow, cuz it's pretty late here. I'm sure the maintainer will also share his thoughts starting tomorrow.

**Comment by ckt114** [comment]
Using your `:LazyRoot` I was able to determine that the `.terraform` folder in the same folder as the opening file is causing this. Is there a way for me to tell it to not use `lsp` folder as the root? Use `.git` folder as root instead?

image

**Comment by dpetka2001** [comment]
1. You could try changing `vim.g.root_spec` in your `options.lua` file, but this will apply to all LSP servers
2. Specifically for the LSP server that you use, you can try the following
```lua
return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        name_of_lsp_server = {
          root_dir = require("lspconfig.util").root_pattern(".git", ".terraform"), -- here order matters so make sure `.git` is before `.terraform`
        },
      },
    },
  },
}
```
3. Alternatively you could change slightly your workflow and open Neovim at the root of the project (I would assume where your `.git` folder is located in your case) and then you can use `<leader><space>` for `root_dir` search and `<leader>fF` for `cwd` search, which would be the directory in which you started Neovim (where your `.git` folder is located).

**Comment by ckt114** [comment]
For #3 I did start nvim from the root git dir but it still having that issue. I'm going to go with your #2 suggestion. Thank you very much for your help.

**Pull request closed without merging**
