### PR TITLE
feat(project): add fzf-lua keymap descriptions

### PR DESCRIPTION
**Pull request by iamxiaojianzheng**
image

### CODE REVIEW

**Comment by folke** [comment]
I'm not sure it's a good idea to change the core actions.
You can just add a `desc = "...."` to those keymaps. Have you tried that? (I fixed that in fzf-lua recently)

**Comment by iamxiaojianzheng** [comment]
> I'm not sure it's a good idea to change the core actions.我不确定更改核心操作是否是个好主意。 You can just add a `desc => I'm not sure it's a good idea to change the core actions. You can just add a `desc = "...."` to those keymaps. Have you tried that? (I fixed that in fzf-lua recently)

Like this ? It not work.
```lua
["ctrl-s"] = {
  function(selected)
    fzf_lua.live_grep({ cwd = selected[1] })
  end,
  { desc = "live_grep" },
},
```

**Comment by iamxiaojianzheng** [comment]
I refer to this issue to implement this feature

https://github.com/ibhagwan/fzf-lua/pull/977

There is another way to add headers, but I think this is too rigid and does not achieve color highlighting.

```lua
fzf_opts = { ["--header"] = "custom header" ]  }
```

**Comment by folke** [comment]
Do it ike this:

```lua
["ctrl-s"] = {
  fn = function(selected)
    fzf_lua.live_grep({ cwd = selected[1] })
  end,
  desc = "live_grep"
}
```

**Comment by iamxiaojianzheng** [comment]
> Do it ike this:
> 
> 
> 
> ```lua
> 
> ["ctrl-s"] = {
> 
>   fn = function(selected)
> 
>     fzf_lua.live_grep({ cwd = selected[1] })
> 
>   end,
> 
>   desc = "live_grep"
> 
> }
> 
> ```

I've tried it, but it doesn't seem to work.

**Comment by iamxiaojianzheng** [comment]
And I checked the code of `fzf-lua` and couldn't find the processing logic of `desc`. Did I miss something?

**Comment by folke** [comment]
ok, I totally misunderstood what you were trying to do here.
My suggestions, simply add the correct help text for when you press `<f1>`.
But you seem to be setting up the header for all the actions.
Do you really think it' a good idea to have all that text there?
Most screens will cut-off the header. Isn't it enough to have the descriptions show up in fzf help?

**Comment by iamxiaojianzheng** [comment]
My idea is that I hope that users can be prompted to perform those operations on the selections like `find files`, otherwise these functions may not be known to users.

Or is there any better way?

**Comment by folke** [comment]
Makes sense. Thanks!

**Comment by ibhagwan** [comment]
> I'm not sure it's a good idea to change the core actions.

This is a part of the code I need to refactor so it’s easier to add automatic headers for “interactive” actions, seeing users have to resort to editing the internal structure hurts my soul as programmer lol

**Pull request merged**
