### PR TITLE
feat(outline): free ctrl-k /ctrl+j

### PR DESCRIPTION
**Pull request by iamxiaojianzheng**
Allows to toggle window in outline using Ctrl-k /ctrl+j

### CODE REVIEW

**Comment by dpetka2001** [comment]
Any specific reason why this should be default instead of something that users change in their personal configuration? What about users that expect the default mapping behavior?

**Comment by iamxiaojianzheng** [comment]
> Any specific reason why this should be default instead of something that users change in their personal configuration? What about users that expect the default mapping behavior?

Because the official default ctrl+j/k and up/down function is repeated, it seems more reasonable to use ctrl+j/k for switching between Windows.

**Comment by dpetka2001** [comment]
Oh sorry. I misunderstood you when you said free the keymaps. You want to be able to move between windows with default LazyVim keymaps that are being used. I see now. You're totally correct. My bad.

**Comment by folke** [comment]
Thanks!

**Pull request merged**
