### PR TITLE
feat(ui): add toggle to show or hide bufferline

### PR DESCRIPTION
**Pull request by bitbirddev**
## Description

Adds a Toggle to show/hide the Bufferline. Keymap tbd.

### CODE REVIEW

**Comment by folke** [comment]
Refactored the code and added this in `keymaps.lua` instead. ty!

**Comment by bitbirddev** [comment]
@folke thank you!

**Comment by bitbirddev** [comment]
btw it says "showtabline" in whichkey which looks a bit off since all other Options start with an uppercase letter. I think "Tabline" woud be a better name.
image


looks like `desc="Tabline"` isn't working here https://github.com/LazyVim/LazyVim/commit/8232651c4a4a80da34f8b6c1742b04144ae4b959

`Snacks.toggle.option("showtabline", {off = 0, on = vim.o.showtabline > 0 and vim.o.showtabline or 2, desc = "Tabline"}):map("<leader>uA")`

Same is true for conceallevel. 

Maybe this is just personal preference.

**Comment by folke** [comment]
good catch. just fixed this on main.

**Comment by bitbirddev** [comment]
thanks again! :)

**Pull request closed without merging**
